### ISSUE TITLE
The latest version of the local development guide is still TBD

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/dev-guide#2]
Hi team,

I see the [latest version of the local development guide](https://kubesphere-dev-guide.netlify.app/zh/get-started/run-kubesphere-locally/) is still TBD. And the initial version of [dev guide](https://github.com/kubesphere/community/blob/master/developer-guide/development/quickstart.md) looks not actively updated and might be out-of-date. Is there any plan to add content to the latest version? 
![image](https://user-images.githubusercontent.com/40452856/173271462-61a339aa-9cd8-45f2-be97-7e4429e5c86a.png)

**Comment by zheng1** [comment]
Most developers are now focused on the v3.3 release, and these documents will be updated after v3.3 released
